### PR TITLE
Fix 'say hello' anchor tag, various SEO / meta title improvements

### PR DESCRIPTION
**Pull request by rochers**
... break.

### CODE REVIEW

**Comment by rochers** [comment]
I also added the words "svbtle dashboard | " to the meta title tag so you can find the dashboard easier when you have two tabs open and one is the wordpress view of the site.

**Comment by rickyrauch** [comment]
@rochers THANK YOU SO MUCH! Great work man.

**Comment by rochers** [comment]
More to come!

**Comment by rickyrauch** [comment]
@rochers Can't wait

**Pull request merged**
